# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
r:
  - release
cache: packages
repos:
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org
